# Exported from https://tiplanet.org/pb/ on Wed Sep  6 20:00:13 2023 (CEST)

# ----------------------------
# Program Options
# ----------------------------

NAME         ?= SITSNY
ICON         ?= icon.png
DESCRIPTION  ?= ""
COMPRESSED   ?= YES
ARCHIVED     ?= YES

# ----------------------------
# Compile Options
# ----------------------------

CFLAGS   ?= -Oz -W -Wall -Wextra -Wwrite-strings
CXXFLAGS ?= -Oz -W -Wall -Wextra -Wwrite-strings

# ----------------------------

include $(shell cedev-config --makefile)
